### ISSUE TITLE
Crashes on exit

### ISSUE THREAD

**Issue by HookedBehemoth** [Sun-Research-University/sys-clk-Overlay#1]
Sometimes crashes on exit.
[01581339766_010000000007e51a.log](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4180872/01581339766_010000000007e51a.log)

**Comment by gabehxd** [comment]
what game was this on?

**Comment by HookedBehemoth** [comment]
Had it on the home menu, in mario odyssey and just now in Trials Rising.
Seems to be more prominent when sys-clk is disabled.

**Comment by gabehxd** [comment]
[sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4187390/sys-clk-Overlay.zip)
can you give this build a try

**Comment by uaevuon** [comment]
> [sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4187390/sys-clk-Overlay.zip)
> can you give this build a try

Same on SMM2

**Comment by gabehxd** [comment]
> > [sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4187390/sys-clk-Overlay.zip)
> > can you give this build a try
> 
> Same on SMM2

can you provide a log

**Comment by uaevuon** [comment]
[01581451227_010000000007e51a.log](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4188012/01581451227_010000000007e51a.log)

**Comment by gabehxd** [comment]
can anyone else reproduce this issue?

**Comment by ghost** [comment]
So far no crashes, everything is running fine. Will test more.

**Comment by gabehxd** [comment]
closing as it seems resolved(?) releasing soon tm

**Comment by uaevuon** [comment]
Still same on SMM2.
https://streamable.com/z6n97

sys-clk-overlay v1.0.2, ovlloader v1.0.2.
My config.ini and log are here.
[config and log.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4248421/config.and.log.zip)

**Comment by gabehxd** [comment]
try this version out
[sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4253444/sys-clk-Overlay.zip)

**Comment by gabehxd** [comment]
@uaevuon

**Comment by uaevuon** [comment]
![IMG_20200227_123932](https://user-images.githubusercontent.com/3542715/75410145-3f2e0580-595e-11ea-8357-e49f5a33b175.jpg)
Not crashing. But it shows this.

**Comment by gabehxd** [comment]
try this out @uaevuon 
[sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4259444/sys-clk-Overlay.zip)

**Comment by uaevuon** [comment]
![ea169199-9462-4653-bdd9-f59ad95b4743](https://user-images.githubusercontent.com/3542715/75413041-bddb7080-5967-11ea-8b3b-9b1f4efa5f2c.jpg)

**Comment by gabehxd** [comment]
[sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4259529/sys-clk-Overlay.zip)
this should be the one

**Comment by gabehxd** [comment]
@uaevuon

**Comment by uaevuon** [comment]
![IMG_20200227_223906](https://user-images.githubusercontent.com/3542715/75450371-06b81700-59b2-11ea-81f0-d9cfd046ea7f.jpg)
Not crashing but similar.

**Comment by gabehxd** [comment]
[sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4265185/sys-clk-Overlay.zip)

**Comment by gabehxd** [comment]
@uaevuon

**Comment by uaevuon** [comment]
Same even on other games.

**Comment by gabehxd** [comment]
[sys-clk-Overlay.zip](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4266017/sys-clk-Overlay.zip) *this should be it*

**Comment by gabehxd** [comment]
@uaevuon

**Comment by uaevuon** [comment]
![IMG_20200229_162129](https://user-images.githubusercontent.com/3542715/75603240-f7e77680-5b0f-11ea-91a8-7115705a5d52.jpg)

Crash on exit. Not just SMM2 but all including on home menu
[01582960904_010000000007e51a.log](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4270026/01582960904_010000000007e51a.log)

**Comment by gabehxd** [comment]
Latest release should fix all issues!
