### ISSUE TITLE
Problem with GPU

### ISSUE THREAD

**Issue by Xebastron** [Sun-Research-University/sys-clk-Overlay#20]
Hello, I have a problem with the OC of the GPU, I have configured it to 900MHZ and the maximum it reaches is 468MHZ, are frequencies above 468 disabled?

Greetings and thank you

**Comment by gabehxd** [comment]
can you check with sys ftpd light that values are changing and in the correct place in the ini

**Comment by Xebastron** [comment]
Solved!!! The GPU have 900MHZ when i connect the NS to USB. 😊

**Comment by gabehxd** [comment]
for future reference those are restrictions put in place by the sysmodule which require the switch be plugged into a power source.
