### ISSUE TITLE
Error: Could not load sys-clk!

### ISSUE THREAD

**Issue by tribes33** [Sun-Research-University/sys-clk-Overlay#25]
Hello, I'm not sure what I can provide for you to properly diagnose the problem, but I am having an issue where it says that I can't load sys-clk, it's not the issue where it says that it cant be found btw, it says "Could not load sys-clk!" I am using the newest version of Tesla overlay, Switch FW 9.2.0 and Atmosphere 0.12.0 if that helps, thanks for any input on this.

**Comment by gabehxd** [comment]
I think your sys clk might be out of date try pulling the latest version from their page

https://github.com/retronx-team/sys-clk/releases/tag/0.13.1

if that doesn't work I can try to make a debug version

**Comment by tribes33** [comment]
Thank you for the fast reply, I'm actually such an idiot! I did not download sys-clk itself, just the overlay, I'm quite tired so I must've overlooked it, it's working perfectly now, thanks for your hard work by the way <3
